name: Build Minecraft Mod

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install System Gradle Tools
      run: sudo apt-get update && sudo apt-get install -y gradle

    - name: Build Mod File
      run: gradle build

    - name: Upload Mod Jar Artifact
      uses: actions/upload-artifact@v4
      with:
        name: HorrorStalkerMod-Jar
        path: build/libs/horrormod-1.0.0.jar
